apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::022745511146:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-17NML7HDREFLL
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::022745511146:role/UdacityFlaskDeployCBKubectlRole
      username: build
kind: ConfigMap
metadata:
  creationTimestamp: "2022-08-31T11:31:27Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1629"
  uid: c10c97a2-96d1-4ee5-b444-2f7dd4813b25
